homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('instagram/', views.instagram, name='instagram'),
    path('story1/', views.story1, name='story1'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'index.html')


def instagram(request):
    return render(request, 'instagram.html')


def story1(request):
    return render(request, 'story1.html')

homepage/templates/base.html
<!DOCTYPE html>

<html>
  <head>
    {% block head_main %} {% endblock %}
  </head>

  <body>
    {% block body_main %} {% endblock %}
  </body>
</html>

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head_main %} 
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Wening Dyah Locitaresmi</title>
    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}" />
{% endblock %} 

{% block body_main %}
<!-- Landing section -->
<div class="landing text-center">
    <div class="d-flex justify-content-center align-items-center">
      <h1 style="color: #514545;">
        H E <span style="color: #D45D79;">L L </span>O
      </h1>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <h6 style="color: #514545;">I'M WENING DYAH LOCITARESMI</h6>
    </div>
    <p>If you want to check out my Instagram page, click <a href="{% url 'homepage:instagram' %}">this link</a>!</p>
    <p><a href="{% url 'homepage:story1' %}">Link to story 1</a></p>
  </div>
  
  <!-- Border -->
  <div section="border">
    <div class="row">
      <div class="col-4 border1"></div>
      <div class="col-4 border2"></div>
      <div class="col-4 border3"></div>
    </div>
  </div>

  <!-- Quote section -->
  <div
    class="quote container justify-content-center align-items-center text-center"
  >
    <h1>"</h1>
    <h5 style="color: #767676;">
      TIME IS TOO SLOW <span style="color: ">FOR THOSE WHO WAIT</span>, TO
      SWIFT <span style="color: black;">FOR THOSE WHO FEAR</span>, TOO LONG
      <span style="color: black;">FOR THOSE WHO GRIEVE</span>, TOO SHORT
      <span style="color: black;">FOR THOSE WHO REJOICE</span>, BUT FOR THOSE
      WHO LOVE, <span style="color: black;">TIME IS ETERNITY</span>
    </h5>
    <br />
    <h1>"</h1>
  </div>

  <!-- About me section -->
  <div class="row">
    <div class="col-lg-4 col-sm-6 container" id="about-me-1">
      <h1 style="font-weight: 700;">About Me</h1>
      <hr>
      <p><span style="font-weight: bold;">Lorem ipsum</span> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
    </h2>
    <div class="col-lg-4 col-sm-6" id="about-me-2" style="padding: 0;">
      <div class="row" id="b-1" style="background-image: url({% static 'fe-rev.jpg' %})">
      </div>
      <div class="row" id="b-2">
        <p><span style="font-weight: bold;">Lorem ipsum</span> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
    </div>
    <div class="col-lg-4 col-sm-12" id="about-me-3">
      <div class="row" id="c-1">
        <p><span style="font-weight: bold;">Lorem ipsum</span> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
      </div>
      <div class="row" id="c-2" style="background-image: url({% static 'manda-rev.jpg' %})"></div>
    </div>
  </div>

  <!-- Academic section -->
  <div class="academic container ">
    <h2 style="margin-bottom: 10vh; text-align: center;">M Y &nbsp; A C A D E M I C &nbsp; P A T H</h2>
    <div class="academic-list">
      <ol class="rectangle-list">
        <li id="bold">Faculty of Computer Science, Universitas Indonesia (2019 - present)
          <ol>
            <li id="un-bold">Human Resource Staff at Pesta Rakyat Komputer 2020</li>
            <li id="un-bold">Human Resource Staff at Compfest 12</li>
          </ol>
        </li>
        <li id="bold">SMAN 2 Kota Tangerang Selatan (2017 - 2019)
          <ol>
            <li id="un-bold">Acceleration program</li>
            <li id="un-bold">Student council officer</li>
          </ol>
        </li>
        <li id="bold">Candle Tree Junior High School (2014 - 2017)
          <ol>
            <li id="un-bold">President of student council</li>
            <li id="un-bold">Silver medal winner, Digital Technologies, ICAS 2016</li>
          </ol>
        </li>
        <li id="bold">Candle Tree Elementary School (2008 - 2014)
          <ol>
            <li id="un-bold">Silver medal winner, Computer Skills, ICAS 2013, 2014</li>
          </ol>
        </li>
      </ol>
    </div>

  </div>

  <!-- Interests section -->
  <div class="interests" style="background-image: url({% static 'band.jpg' %})">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <h1 style="color: white; text-align: center;">W H A T &nbsp; I ' M  &nbsp;<span style="color: #D45D79;">I N T E R E S T E D</span> &nbsp; A T</h1>
      </div>
      <div class="row pt-4">
        <div class="col-6">
          <hr align="right" id="hr-1"><br>
          <hr align="right" id="hr-2"><br>
          <hr align="right" id="hr-3">
        </div>
        <div class="col-6" style="padding-top: 12px;">
          <h4 style="margin-bottom: 19px;">Music</h4><br>
          <h4 style="margin-bottom: 19px;">Information technology</h4><br>
          <h4>Graphic design</h4>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio section -->
  <div class="portfolio text-center">
    <h1>PORTFOLIO</h1>
    <h5 style="font-weight: bold; margin-bottom: 15vh;">HERE IS A LIST OF THINGS THAT I HAVE DONE THOROUGH MY STUDY</h5>
      <div class="row">
        <div class="col-lg-3 col-md-4 content" id="p-item">
          <div class="content-overlay"></div>
          <img src="{% static 'p1.jpg' %}" alt="" srcset="">
          <div class="content-details fadeIn-bottom">
            <h3 class="content-title">Project Name</h3>
            <p class="content-text">A short description</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 content" id="p-item">
          <div class="content-overlay"></div>
          <img src="{% static 'p2.jpg' %}" alt="" srcset="">
          <div class="content-details fadeIn-bottom">
            <h3 class="content-title">Project Name</h3>
            <p class="content-text">A short description</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 content" id="p-item">
          <div class="content-overlay"></div>
          <img src="{% static 'p3.jpg' %}" alt="" srcset="">
          <div class="content-details fadeIn-bottom">
            <h3 class="content-title">Project Name</h3>
            <p class="content-text">A short description</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 content" id="p-item">
          <div class="content-overlay"></div>
          <img src="{% static 'p4.jpg' %}" alt="" srcset="">
          <div class="content-details fadeIn-bottom">
            <h3 class="content-title">Project Name</h3>
            <p class="content-text">A short description</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 col-md-4 content" id="p-item">
          <div class="content-overlay"></div>
          <img src="{% static 'p5.jpg' %}" alt="" srcset="">
          <div class="content-details fadeIn-bottom">
            <h3 class="content-title">Project Name</h3>
            <p class="content-text">A short description</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 content" id="p-item">
          <div class="content-overlay"></div>
          <img src="{% static 'p6.jpg' %}" alt="" srcset="">
          <div class="content-details fadeIn-bottom">
            <h3 class="content-title">Project Name</h3>
            <p class="content-text">A short description</p>
          </div>
        </div>
      </div>
    
  </div>

  <!-- Contact section -->
  <div class="contact">
    <div class="container text-center">
    <h5>LOOKS LIKE YOU'VE REACHED THE END OF THE PAGE.<br>
    IF YOU WANT TO TALK WITH ME, YOU CAN FIND ME<br>
    ON MY SOCIAL MEDIAS</h5><br>
    <h5>YOU CAN ALSO MAIL ME <a href="https://mail.google.com/mail/?view=cm&fs=1&to=weninglc@gmail.com" target="_blank" style="color: #BC5090;">HERE</a>!</h5>
    <br><br>
    <a href="https://www.linkedin.com/in/weningdyahlocitaresmi/" target="_blank">
      <img src="{% static 'Linkedin.png' %}" alt="">
    </a>
    <a href="https://www.instagram.com/weninglc/" target="_blank">
      <img src="{% static 'Instagram.png' %}" alt="">
    </a>
    <a href="https://github.com/weninglc" target="_blank">
      <img src="{% static 'Github.png' %}" alt="">
    </a><br><br><br>
    <p>C O D E D &nbsp; W I T H &nbsp; 💖 &nbsp; B Y &nbsp; M E</p>
  </div>
  </div>

  <!-- Another border -->
  <div section="border">
    <div class="row">
      <div class="col-4 border1"></div>
      <div class="col-4 border2"></div>
      <div class="col-4 border4"></div>
    </div>
  </div>
{% endblock %}

homepage/templates/instagram.html
{% extends 'base.html' %} {% load static %} {% block head_main %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Wening Dyah Locitaresmi | Instagram</title>
<link rel="stylesheet" href="{% static 'style.css' %}" />
<link rel="stylesheet" href="{% static 'bootstrap.css' %}" />
{% endblock %} {% block body_main %}
<div class="landing">
  <h1>I'm sorry, looks like you've went to the wrong page :(</h1>
  <br />
  <p>
    Click <a href="{% url 'homepage:index' %}">this link </a>to go back or click
    <a href="https://www.instagram.com/weninglc/">this link</a> to go to my
    actual Instagram page
  </p>
</div>
{% endblock %}

homepage/templates/navbar.html
{% extends 'base.html' %} {% load static %} {% block head_main %}
<div class="row mr-5 pr-5">
  <div class="col-6 mt-3">
    <a class="navbar-brand" href="#">
      <img src="./images/logo.png" height="100px" alt="" />
    </a>
  </div>
  <div class="col-6 mt-3">
    <div class="nav p-3 justify-content-end">
      <div class="menu">
        <a href="#about">About </a>
        <a href="#projects">Projects </a>
        <a href="#contact">Contact</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

homepage/templates/story1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Personal Biodata</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Rufina&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="style.css" />
  </head>

  <body>
    <div class="head">
      <div class="row">
        <div
          class="col-lg-6 col-sm-12 text-left justify-content-center"
          id="satu"
        >
          <h4>Kenalin! Namaku..</h4>
          <h3>Wening Dyah Locitaresmi</h3>
          <p>Mahasiswa semester dua Fasilkom UI 2019 dengan NPM 1906299194</p>
          <p>
            <i
              >*Foto di samping diambil saat pelaksanaan wisuda ganjil Fasilkom
              2020</i
            >
          </p>
        </div>
        <div class="col-lg-6 col-sm-12" id="dua">
          <img src="./Images/band.jpg" alt="" />
        </div>
      </div>
    </div>
    <div class="head2">
      <div class="container pt-5 text-center">
        <h4>Mau tau tentang diriku?</h4>
        <br />
        <section class="company-heading intro-type" id="parallax-one">
          <div class="container">
            <div class="row product-title-info">
              <div class="col-md-12">
                <a href="#section2"
                  ><img
                    alt="Arrow Down Icon"
                    src="https://www.solodev.com/assets/anchor/arrow-down.png"
                /></a>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>

    <div class="body" id="section2">
      <div class="container pt-5 text-center">
        <div class="row">
          <div class="col-lg-4 col-sm-6 pb-5">
            <p>
              Aku lahir di Yogyakarta, 16 Januari 2002. Aku besar di daerah
              Tangerang Selatan dan hanya sempat mencicipi manisnya suasana
              hidup kota Yogyakarta selama 3-4 tahun.
            </p>
            <p>
              Minatku terpaku pada dunia IT dan musik. Besar harapanku agar
              keduanya dapat terus menjadi bagian dari hidupku.
            </p>
          </div>
          <div class="col-lg-4 col-sm-6 pb-5">
            <p>
              Pengalamanku mungkin tidak sebanyak yang orang lain miliki. SMA
              hanya kutempuh selama dua tahun karena aku ditempatkan di kelas
              akselerasi. Berikut adalah perjalanan akademisku hingga saat ini
            </p>
            <ul class="text-left">
              <li>Candle Tree Elementary School</li>
              <li>Candle Tree Junior High School</li>
              <li>SMAN 2 Kota Tangerang Selatan</li>
              <li>Fasilkom Universitas Indonesia, Jurusan Sistem Informasi</li>
            </ul>
            <p>
              Meskipun tidak banyak, namun aku bersyukur pernah memegang amanah
              dalam beberapa kegiatan kepanitiaan dan organisasi, seperti ketua
              OSIS
            </p>
          </div>
          <div class="col-lg-4 col-sm-12 pb-5">
            <p>
              Ingin mengenalku lebih lanjut? Kalian dapat menghubungiku melalui
              kontak yang tersedia di bawah ini
            </p>
            <br />
            <p>
              <a href="https://www.instagram.com/weninglc/">
                <img src="./Images/ig.png"
              </a>
            </p>
            <p>
              <a href="http://line.me/ti/p/~weninglc">
                <img src="./Images/line.png"
              </a>
            </p>
            <p>
              <a href="https://www.linkedin.com/in/weningdyahlocitaresmi/">
                <img src="./Images/linkedin.png"
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>